# Generated by Django 4.2 on 2023-04-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oyuncu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('dogum_tarihi', models.DateField()),
                ('ulke', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yonetmen', models.CharField(max_length=100)),
                ('yil', models.IntegerField()),
                ('aciklama', models.TextField()),
                ('oyuncular', models.ManyToManyField(to='appMy.oyuncu')),
            ],
        ),
        migrations.CreateModel(
            name='Dizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yonetmen', models.CharField(max_length=100)),
                ('yil', models.IntegerField()),
                ('sezon_sayisi', models.IntegerField()),
                ('bolum_sayisi', models.IntegerField()),
                ('aciklama', models.TextField()),
                ('oyuncular', models.ManyToManyField(to='appMy.oyuncu')),
            ],
        ),
    ]
